name: Build for Linux ARM
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
 
    - name: Set up Linux ARM
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: "armv7-unknown-linux-gnueabihf"
        override: true
 
    - name: Build
      run: cargo build --target=armv7-unknown-linux-gnueabihf --release
