name: Build and Release ARM64 Binary

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          pip install fastapi pyinstaller pywebview uvicorn

      - name: Build ARM64 executable
        env:
          CFLAGS: "-march=armv8-a"
          CC: aarch64-linux-gnu-gcc  # 指定交叉编译器
        run: |
          pyinstaller --onefile --name fastapi_app app.py
          file ./dist/fastapi_app  # 确认文件类型

      - name: Create release if needed
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          body: "Release for Linux ARM64"
          draft: false
          prerelease: false

      - name: Upload ARM64 binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/fastapi_app
          asset_name: fastapi_app-arm64
          asset_content_type: application/octet-stream
