name: Build and Release FastAPI for Linux ARM64

on:
  push:
    tags:
      - "v*"  # 匹配所有以 "v" 开头的 Tag

jobs:
  build-and-release-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi==0.108.0
          pip install pyinstaller==6.3.0
          pip install pywebview==4.4.1
          pip install uvicorn==0.25.0

      - name: Prepare cross-compilation for ARM64
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build executable for Linux ARM64
        run: |
          pyinstaller --onefile --name fastapi_app app.py \
          --distpath ./dist/arm64

      - name: Archive executable
        run: |
          tar -czvf fastapi_app-linux-arm64.tar.gz -C ./dist/arm64 fastapi_app

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release for ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fastapi_app-linux-arm64.tar.gz
          asset_name: fastapi_app-linux-arm64.tar.gz
          asset_content_type: application/gzip
