name: Build and Release ARM64 Binary

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install fastapi pyinstaller pywebview uvicorn
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build ARM64 executable
        env:
          # 设置 ARM64 架构，使用交叉编译工具 gcc-aarch64-linux-gnu
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          AR: aarch64-linux-gnu-ar
          LD: aarch64-linux-gnu-ld
          CFLAGS: "-march=armv8-a"
        run: |
          # 通过 PyInstaller 打包生成 ARM64 可执行文件
          pyinstaller --onefile --name fastapi_app app.py

      - name: Create release if needed
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          body: "Release for Linux ARM64"
          draft: false
          prerelease: false

      - name: Upload ARM64 binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/fastapi_app
          asset_name: fastapi_app-arm64
          asset_content_type: application/octet-stream
