name: release

on:
  push:
    tags:
      - v*

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install fastapi pyinstaller pywebview uvicorn
      - name: Build executable for ARM64
        run: |
          pyinstaller --onefile --name fastapi_app app.py \
          --distpath ./dist/linux-arm64 --target-arch arm64
      - name: Upload executables
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/linux-arm64/fastapi_app
          asset_name: fastapi_app-linux-arm64
          asset_content_type: application/octet-stream
